spring:
    application:
        name: authentication
    
    datasource:
        url: jdbc:mysql://localhost:3306/authentication
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        hibernate:
            ddl-auto: update
            
jwt:
    secret-key: PHUXUYENhanoib20dccn503D20CNPM6d20cqcn11bhospitalsystemDOANTOTNGHIEP2024DINHMINHPHUC24052002
    access-token=expiration: 300000
