server:
    port: 8088

spring:
    application:
        name: ExaminationResult
    
    datasource:
        url: jdbc:mysql://localhost:3306/examination_result
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        hibernate:
            ddl-auto: update
        
    kafka:
        bootstrap-servers:
            - localhost:9092
        producer:
            key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
            key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
    
    main:
        allow-bean-definition-overriding: true
jwt:
    secret-key: PHUXUYENhanoib20dccn503D20CNPM6d20cqcn11bhospitalsystemDOANTOTNGHIEP2024DINHMINHPHUC24052002
    access-token=expiration: 300000

kafka:
    topics:
        create-examination-topic: create_examination_result_from_greeting
    group-id:
        examination-result: examination_result

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true
    
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
        hostname: localhost