spring:
    application:
        name: ApiGateway

    cloud:
        gateway:
            routes:
                - id: faculty
                  uri: lb://FACULTY
                  predicates:
                      - Path=/api/v1/faculty/**
                
                - id: authentication
                  uri: lb://AUTHENTICATION
                  predicates:
                    - Path=/api/v1/authentication/**
            
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
            globalcors:
                cors-configurations:
                    '[/api/v1/**]':
                        allowedOrigins: "*"
                        allowedHeaders: "*"
                        allowedMethods:
                            - GET
                            - POST
            

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 9000